### PR TITLE
add bundle_without option

### PR DESCRIPTION
**Pull request by masarakki**
I'm using ruby-2.3.0, but alpin has ruby-2.2.3, so `bundle install` installs all gems once more.
I added `deploy` gem group to my app, and I want to run `bundle install --without default development test production` to install gems only for deployment.

### CODE REVIEW

**Comment by tboerger** [comment]
This won't work, you have to add the new json field to the struct

**Comment by tboerger** [comment]
LGTM
But @bradrydzewski already said that this plugin will be dropped from the official plugin list as it executes arbitrary code.

**Comment by bradrydzewski** [comment]
this repository is deprecated and will eventually be deleted. more details at https://github.com/drone-plugins/drone-capistrano/issues/2#issuecomment-171814186

**Comment by bradrydzewski** [comment]
I should add a note here -- this plugin will be deleted as an official drone plugin, however, you are free to maintain this as an unofficial plugin under your own dockerhub account

**Comment by glaszig** [comment]
@masarakki i'm maintaining this plugin in an unofficial matter over at [my fork](https://github.com/glaszig/drone-capistrano). it is now based on the official ruby:2.3-alpine docker image.

**Pull request closed without merging**
